### ISSUE TITLE
libpng warning: IDAT: Extra compressed data

### ISSUE THREAD

**Issue by ashpil** [image-rs/image-png#262]
I seem to be getting this warning on finishing writing a png with a `StreamWriter`:
```
libpng warning: IDAT: Extra compressed data
```
I can't seem to find any information about whether it is harmless or not. Doing the exact same operation, but not using a `StreamWriter`, does not produce a warning. What might this imply?

If it is truly harmless and unavoidable, it would be nice to have an option to suppress the warning.

**Comment by fintelia** [comment]
Are you seeing any corruption in the image contents? If not, then it is probably harmless but still something that should be tracked down and fixed.

**Comment by ashpil** [comment]
As far as I can tell, the image is identical, but I can't actually confirm that because my use-case has a bit of randomness to it.

**Comment by scurest** [comment]
This is caused by an off-by-one error in `ChunkWriter::flush`.

https://github.com/image-rs/image-png/blob/26f8f8bbc8dab63ba4aa34146016166203f7f9c0/src/encoder.rs#L401

Should be `..self.index`. Since the buffer is extremely unlikely to be exactly full at the end, this will write one extra byte at the end of the zlib stream, causing "extra compressed data".

-----

There's another much rarer error in `ChunkWriter::write`:

https://github.com/image-rs/image-png/blob/26f8f8bbc8dab63ba4aa34146016166203f7f9c0/src/encoder.rs#L387

If the index happens to be `self.buffer.len() - 1`, the buffer get written out with one extra byte. This causes a similar error, "invalid stored block lengths".
