### ISSUE TITLE
Not possible to encode multiple individual, non-animation images with the same encoder instance

### ISSUE THREAD

**Issue by sdroege** [image-rs/image-png#301]
This was possible with 0.16 but with 0.17 this causes the `EndReached` error.

**Comment by HeroicKatora** [comment]
Just to confirm this with you, is this issue about 'Conforming behavior'? Since the specification states:



Chunk name | Multiple allowed | Ordering constraints
-- | -- | --
IDAT | Yes | Multiple IDAT chunks shall be consecutive

I suppose a _lenient_ interpretation of the specification would infer that it's okay to have multiple IDAT images if, and only if, they are immediately consecutive. Is this what you're trying to do? The change with `0.17` was to consequently enforce the number of frames written according to the animation control but I can see that this can be undesirable.

**Comment by sdroege** [comment]
Either that, or providing a way to "reset" the encoder so it's back in its initial state.

**Comment by HeroicKatora** [comment]
Can you clarify specifically if you are interesting in writing _other_ chunks between the multiple images?

**Comment by sdroege** [comment]
I don't need that, no.

**Comment by HeroicKatora** [comment]
Fixed in `0.17.2`.
