### ISSUE TITLE
Decoding fails with LimitsExceeded despite not exceeding limits

### ISSUE THREAD

**Issue by sophie-h** [image-rs/image-png#431]
The problem is this code

https://github.com/image-rs/image-png/blob/8afa7ef01ffe7b4ed92cbb768aa0d7ea6a3acc77/src/decoder/stream.rs#L776-L777

I got an issue with an image that triggers this problem https://gitlab.gnome.org/sophie-h/glycin/-/issues/28 generated with draw.io

I don't understand the code enough on the first look to fix it.

**Comment by fintelia** [comment]
The good news is that the relevant code has been significantly simplified since that FIXME was added.  The general changes needed to properly enforce limits are:

* Move `Reader::limits` to be `StreamingDecoder::max_bytes` that defaults to `usize::MAX` but is initialized to the chosen allocation limit when used inside a `Reader`.
* Have the current limits check in Reader instead decrement the max_bytes field on its contained streaming reader.
* Update the current hardcoded limits to instead decrement the max_bytes value by the amount allocated (using something like `checked_sub(bytes).ok_or(LimitsExceeded)?`)
* [Optional:] review the contents of _src/decoder/mod.rs_ and _src/decoder/stream.rs_ for any other places that might do large allocations and enforce the limits there as well
